### PR TITLE
some helpers

### PR DESCRIPTION
**Pull request by bkodes**
Opening this to start discussion to see if I could help with the project? Very interested in this endeavor

### CODE REVIEW

**Comment by pengzhangzhi** [comment]
The proposal is interesting. DNA sequences are Utral long, a long-context and memory-efficient transformer might be able to discover new insight into the genomes. This work has great potential for Computational biology research. I am in! Wondering what can I do to help with this project.

**Comment by lucidrains** [comment]
hey, thanks for the interest :smiley: :dna: 

yea, i could definitely use help with both the data and crafting of the evaluation sets

**Comment by bkodes** [comment]
> hey, thanks for the interest :smiley: :dna: 
> 
> 
> 
> yea, i could definitely use help with both the data and crafting of the evaluation sets
> 
> 

Awesome. Would love to help!

**Comment by bkodes** [comment]
@lucidrains My CEO wanted me to ask you about an inquiry our company Air AI has so I sent you an email. Is the email in your bio the best way of getting in contact with you for business inquiries?

**Comment by joseph-c-kim** [comment]
Hi @lucidrains, I would love to help and contribute to this! I've done some work previously on predicting gene expression levels based on DNA methylation data. Would you prefer to talk more in detail on Github or email?

**Pull request closed without merging**
